import requests

# --- PEGUE SU SENTENCIA REAL ENTRE LAS TRES COMILLAS ---
texto_real = """Posadas, 02 de febrero de  2026
CAUSA: "Expte Nº 117742/2023 REGALADO JUAN JOSÉ c/ BAR ESPAÑOL SRL s/ ACCIONES LABORALES DE TRÁMITE ORDINARIO” para dictar sentencia;
ANTECEDENTES: 
En autos comparece el Sr. Juan José Luján  Regalado interponiendo formal demanda a id. 22256858 - en contra de Bar Español S.R.L en procura del cobro de la suma de $7.411.010,77 en concepto de indemnización por despido indirecto, conforme planilla de liquidación obrante en el punto III del escrito de demanda.
Manifestó que ingresó a trabajar para la firma demandada el 27 de abril de 2005, en relación de dependencia. Indicó que cumplía una jornada laboral que se extendía de lunes a viernes de 10:00 a 18:00 horas, y a partir de los días miércoles o jueves de 10:00 a 20:00 horas. Señaló además que trabajaba los sábados y domingos de 04:00 a 16:00 horas, y que en algunas ocasiones también rotaba en el horario de 10:00 a 20:00 horas durante los días de semana.
Expresó que, si bien los recibos consignaban la categoría de Cajero–Adicionista, en realidad desempeñó funciones correspondientes a la categoría de Encargado – Categoría 6, cumpliendo tareas de alta responsabilidad tales como: manejo de personal, control de stock y mercaderías, pagos a proveedores y empleados, tareas administrativas, diseño y actualización de cartas de menú, atención de inspecciones de AFIP, Municipalidad, Bromatología y Ministerio de Trabajo, atención telefónica, cobranzas, manejo de cuentas bancarias, transferencias, preparación de planillas y arqueo de caja, entre otras.
Relató que los francos nunca le fueron otorgados conforme la ley, sino según la conveniencia de la empresa. Sostuvo que percibió una remuneración inferior a la que le correspondía por su verdadera categoría, y que las horas extras no le fueron retribuidas, ni siquiera como horas simples, pese a sus reiterados reclamos. Afirmó también que desde el inicio de la relación laboral la patronal incumplió diversas obligaciones registrales y salariales.
Refirió que, frente a la negativa persistente de la empresa, intimó mediante telegrama ley en fecha 18/10/2022 para que se regularizara su categoría y salario, y abonara el sueldo adeudado del mes de septiembre de 2022, cuyo pago había sido negado a pesar de los reclamos efectuados por su esposa ante la patronal. Explicó que no podía mantener contacto directo con los empleadores por indicación médica, debido al grave cuadro depresivo que padecía, motivado por la hostilidad, el maltrato y la persecución ejercida por los socios de la empresa, quienes eran además su hermana Débora Natalia Regalado y su cuñado Cristian Orué.
Indicó que durante los primeros años de trabajo planteó su reclamo por la correcta categoría laboral, pero su hermana le manifestó que no existía otra categoría superior. Agregó que, a pedido de ella, el contador de la firma le dejó una supuesta copia de categorías, de la cual surgía que estaba correctamente registrado. 
Narró que, pese a ello, en algunas oportunidades la patronal comenzó a abonarle sumas en negro, independientes del recibo de haberes. Expresó que, al advertir la irregularidad de la situación y asesorarse con terceros, renovó sus reclamos, recibiendo reiteradas promesas de regularización que nunca fueron cumplidas, a pesar de que la empresa lo dejaba a cargo del negocio durante prolongadas ausencias de los socios.
Manifestó que, a partir de la pandemia, la situación se agravó, ya que la patronal sólo abonaba la asistencia estatal, obligando a los empleados a firmar recibos que no reflejaban lo efectivamente percibido.
Expuso que todas estas circunstancias generaron un ambiente de hostilidad y persecución hacia su persona, lo cual fue conversado personalmente con los socios, quienes se valieron de la relación de parentesco existente para convocarlo a trabajar y luego exigirle responsabilidades superiores sin reconocimiento salarial.
Relató que la situación tuvo su punto crítico el 20 de mayo de 2022, cuando fue suspendido por diez días, por un supuesto hecho de violencia con el cocinero Fernando Ariel Prieto. Señaló que la suspensión fue injusta y unilateral, pese a que era de público conocimiento el temperamento violento del Sr. Prieto, quien incluso tenía antecedentes de violencia familiar. 
Describió los hechos del día referido, afirmando que Prieto lo insultó, lo amenazó con un cuchillo y adoptó conductas hostiles, y que el disturbio finalizó con un empujón y la salida voluntaria del cocinero del local. Indicó que la patronal, pese a conocer el contexto y pruebas presentadas, decidió suspenderlo solo a él, reforzando la persecución laboral que venía padeciendo.
Sostuvo que esta situación, sumada a la falta de reconocimiento de su categoría, el exceso de horas trabajadas, la carga de responsabilidades y los malos tratos, derivó en un cuadro depresivo severo y episodios de ansiedad, acreditados con certificados médicos presentados a la empleadora.
Explicó que, paralelamente, denunció su situación ante AFIP por incorrecta registración y cursó diversas intimaciones telegráficas para la regularización laboral y el pago de haberes adeudados, todas ellas rechazadas por la empresa mediante cartas documento en las que negaron los hechos y ratificaron la categoría de Cajero–Adicionista.
Señaló que la real categoría que ejercía se corroboraba incluso con los dichos del propio Sr. Prieto en sede policial y judicial, donde lo identificó explícitamente como su “encargado”. Indicó también que el socio gerente, Cristian Orué, declaró en sede judicial haber observado los hechos a través de cámaras de seguridad, afirmación que demuestra la intención disciplinaria dirigida únicamente hacia su persona.
Finalmente, manifestó que formalizó una denuncia ante el Ministerio de Trabajo de la Provincia (Expte. Nº 1473/2023), donde la empresa nuevamente negó sus reclamos. Sostuvo que, ante la persistente negativa patronal, la falta de pago de salarios, la incorrecta registración y el ambiente hostil que afectó gravemente su salud, se configuró el distracto laboral imputable al empleador, motivo por el cual reclama las indemnizaciones y créditos laborales adeudados.
Practicó planilla de liquidación. Ofrece pruebas. Funda en derecho y peticiona.
Bajo id. 22697515 compareció la demandada Bar Español S.R.L, contestó demanda y negó en forma general y categórica todos y cada uno de los hechos indicados en demanda.
Negó todas las circunstancias que pretendió atribuirse, como fecha de ingreso, jornadas que jamás cumplió, tareas que nunca realizó y una categoría superior que no le correspondía según el Convenio Colectivo 389/04.
Explicó que el conflicto no había surgido por supuestos incumplimientos patronales, sino a raíz de un episodio ocurrido el 20 de mayo de 2022. Ese día tomó conocimiento de un altercado entre el actor y un cocinero del bar. Al revisar las cámaras de seguridad del local, se observó claramente que el actor se dirigió hacia su compañero y lo agredió físicamente sin que hubiera existido provocación previa. Frente a esa falta grave, decidió imponer una suspensión disciplinaria de diez días, plenamente justificada.
Al finalizar la suspensión, el actor no regresó a cumplir sus tareas y  comenzó a presentar certificados médicos alegando un cuadro de “estrés laboral”. En ese período solicitó además sus vacaciones, que le fueron otorgadas. Una vez concluido ese descanso, continuó presentando nuevas licencias médicas. Ante tal situación, solicitó una junta médica ante el Ministerio de Trabajo, de la cual tuvo pleno conocimiento.
Fue a partir de esa convocatoria que el actor comenzó a reclamar una categoría que nunca tuvo ni le correspondía. Sostuvo que debía registrarse como “encargado”, figura que no existe en el Convenio para establecimientos gastronómicos. Aprovechando su situación médica y anticipando que sería dado de alta para retomar tareas, empezó a formular reclamos infundados que culminaron en su decisión de darse por despedido indirectamente.
Expuso también que el actor siempre estuvo correctamente registrado como cajero adicionista, categoría que sí se encuentra prevista en el convenio. Nunca realizó tareas de dirección, manejo de personal, contratación o despido de trabajadores, compras mayores, controles administrativos, gestiones ante AFIP o Municipalidad, ni manejo de cuentas bancarias. Sus funciones se limitaron a las propias de un cajero: cargar pedidos, controlar la salida de platos, cobrar a los clientes, entregar vueltos y realizar pequeños pagos o adelantos autorizados por el socio gerente.
Aclaró que, lejos de sufrir persecución o maltrato, el actor recibió beneficios especiales por su vínculo familiar con una de las socias. Asistía a eventos de música electrónica varios días al año sin sufrir descuentos y, además, recibía una gratificación mensual por fuera de su sueldo como ayuda familiar.
Relató que el actor jamás sufrió incorrecta categorización, hostilidad ni incumplimiento alguno por parte de la empleadora. Por el contrario, su decisión de autodespedirse fue una maniobra destinada a evitar su reincorporación luego de la suspensión disciplinaria y la junta médica solicitada.
Sostuvo que ninguno de los rubros reclamados resultan procedentes, ya que el actor estaba correctamente registrado, cobraba lo que correspondía y todas las obligaciones laborales se encontraban debidamente cumplidas.
Ofrece pruebas. Funda en derecho. Reserva caso federal. Peticiona.
Bajo id Nº 23058378, el actor contestó el traslado corrido a los fines del art. 83 del C.P.L. A id 24687590 se fijó fecha de conciliación, la cual se llevó a cabo conforme acta obrante a id 25122178 y se abrió la causa a pruebas. Producidas las ofrecidas por las partes según informe actuarial id N° 29974522, se clausuró el término probatorio y se puso el expediente a disposición de las partes para alegar, habiendo ambas partes hecho uso de su derecho, según informe del actuario id 30615103. Bajo el mismo id se llaman autos para dictar sentencia, efectivizándose conforme constancia id Nº 30712359.
ANÁLISIS DE LA CONTROVERSIA:
Tal como fuera trabada la litis, toda vez que la parte demandada reconoce expresamente que el Sr. Regalado ingresó a laborar bajo sus órdenes el día 27/04/2005, la controversia se circunscribe a determinar si el despido indirecto, remitido el día 12/12/2022 (fs. 43), mediante CD Nº 205099594, resultó justificado y si prosperan las pretensiones indemnizatorias derivadas del distracto que persigue el actor.
No estando controvertida la relación laboral ni la fecha de ingreso en primer lugar me avocare a analizar la controversia en cuanto a la categoría que ejecutaba el actor desde su ingreso hasta la extinción del vínculo y luego el distracto.
I.- Controversia en torno a la categoría
El actor afirma, según las tareas realizadas, que debía ser categorizado como “encargado, categoría 6” del CCT Nº 389/04. Del otro lado, la demandada afirma que desde el inicio se desempeñó como “cajero adicionista”.
Ahora bien, respecto a la carga de la prueba, debe tenerse presente lo establecido por el art. 96 del CPL:"...incumbe la carga de la prueba a la parte que afirma un hecho controvertido o de un precepto jurídico que el Juez o Tribunal no tiene el deber de conocer. Cada una de las partes debe probar el presupuesto de hecho de la norma o normas que invoca como fundamento de su pretensión, defensa o excepción...”. 
Así pues, es el trabajador quien debe acreditar que cumplió las tareas mencionadas en tal declaración. Para ello se vale de la prueba testimonial.
En primer lugar el testigo Aníbal Ricardo Kuhn (id. 25490432) se desprende con claridad que el Sr. Regalado desarrolló tareas en el Bar Español SRL desde aproximadamente el año 2005 hasta el año 2022, desempeñando no sólo tareas de cajero –categoría con la que se hallaba registrado– sino cumpliendo de manera habitual y permanente funciones que califica como propias de un encargado general. Realizaba tareas tales como la apertura del local, manejo de llaves y alarmas, recepción de proveedores, realización de depósitos y pagos, atención de inspecciones, organización de francos, vacaciones y vales del personal, así como la administración cotidiana del establecimiento. 
El testigo, cuya declaración resultó coherente, verosímil y fundada en percepciones directas, describió además condiciones laborales deficientes, con personal no registrado, descuentos indebidos de haberes y un trato patronal calificado como hostil y despectivo, incluyendo discusiones y descalificaciones hacia el actor cuando reclamaba el reconocimiento de sus reales funciones y una mejora salarial. 
Luego, del testimonio del Sr. Cristian Jhonatan Barrios, id. 25492707, se desprende que el Sr. Regalado se desempeñó en el Bar Español como encargado general, pese a figurar registrado como cajero, extremo que el testigo afirma conocer desde su ingreso, dado que el actor ya ejercía funciones jerárquicas y de administración. Describe que Regalado cumplía tareas propias de un encargado: pago de sueldos, trato con proveedores, realización de transferencias y trámites ante AFIP y Municipalidad, organización del personal, francos y horarios, todo lo cual demuestra el ejercicio habitual y continuo de funciones superiores a su categoría registral. Asimismo, la declaración da cuenta de condiciones laborales irregulares y un trato patronal hostil, incluyendo amenazas cuando se reclamaban derechos, trabajo parcialmente no registrado y reducción salarial durante la pandemia. Señala también que el actor decidió su desvinculación por el cansancio derivado de la falta de reconocimiento de su real categoría y las diferencias salariales. 
También se valió del testimonio del Sr. Ricardo Rodrigo Fernández, id. 25494258, el cual afirma que conoció al actor por haber trabajado junto a él en el Bar Español desde el año 2005, señalando que desde entonces ya cumplía funciones de encargado general, pese a estar registrado como cajero. Detalla que el actor trabajaba en turnos rotativos y jornadas que excedían con habitualidad las 8 horas, incluso llegando a 12 hs, y que se mantuvo en el establecimiento hasta “hace poco”, lo cual coincide temporalmente con la desvinculación denunciada. El testigo brinda una descripción clara de las tareas desempeñadas por Regalado: actuar como nexo con la patronal, realizar depósitos, trámites ante AFIP y Municipalidad, organizar al personal, contratar y despedir empleados, otorgar adelantos, pagar salarios y ejercer la representación visible del establecimiento, lo que evidencia de manera categórica la prestación de tareas de jerarquía superior a su categoría registrada. Asimismo, su declaración expone condiciones laborales precarias, tales como la registración parcial de horas, jornadas extendidas, pagos fraccionados mediante vales y la realización de tareas extras en el domicilio de los dueños. Finalmente, atribuye la salida del actor al reiterado reclamo de su correcta categoría y salario. 
Por último el testigo Jorge Antonio Azame, id. 25496476,  ex dependiente del Bar Español SRL afirmó que conoció al actor en dicho establecimiento, donde —desde su ingreso en 2006— ya se desempeñaba como encargado, pese a figurar registrado como cajero adicionista. Describió con precisión las amplias funciones que cumplía el actor: manejo de personal, organización de vacaciones y francos, recepción de insumos, solución de averías, pagos y depósitos bancarios, apertura y cierre del local (teniendo llave del establecimiento) y atención integral de la operatoria diaria, incluso durante las ausencias de los dueños, quienes viajaban con frecuencia. Manifestó que el actor ejercía dichas tareas con buen trato y en forma acorde a un encargado general. Asimismo, detalló las graves irregularidades laborales del establecimiento: pagos fuera de término y en cuotas, presencia de personal no registrado, jornadas de 9 a 12 horas sin abonar horas extras, ambiente de trabajo tenso y con maltratos, mala organización interna y exigencias fuera de categoría. 
También ratificó que el propio actor reclamaba reiteradamente su recategorización, por considerar que sus tareas excedían la categoría de cajero. Finalmente, al describir las funciones propias del cajero adicionista, el testigo dejó en claro que no coincidían con las múltiples responsabilidades asumidas por el Sr. Regalado, confirmando de manera contundente la desnaturalización funcional y la mayor jerarquía real del actor.
Luego de los testigos de la parte demandada, en primer lugar prestó declaración el Sr. Ramón Antonio Cavallero, id. 25509599, quien manifestó que conoce al actor por haber trabajado juntos en el Bar Español y que actualmente continúa empleado allí. Indicó que Regalado realizaba tareas de cajero, igual que él. La mayoría de las preguntas del pliego original fueron desistidas. En las preguntas ampliatorias formuladas por la demandada, afirmó que todas las tareas de manejo y administración del bar (manejo de personal, contrataciones, despidos, atención a proveedores, control de stock, pagos, tareas administrativas, controles de AFIP, inspecciones y manejo de cuentas bancarias) eran realizadas por los dueños Cristian Orúe y Débora Regalado.
En las repreguntas, precisó su fecha de ingreso (junio 2014), horarios de trabajo, funciones anteriores (mozo), que nunca realizó entregas fuera del local, y describió que los dueños estaban siempre presentes o comunicados por grupos de WhatsApp. También explicó el sistema de vales, forma de pago de salarios, banco utilizado (Santander Río), su tipo de cuenta y la dinámica de trabajo nocturno. Indicó además que él tiene llave del local al cerrar, y un cocinero al abrir. 
En segundo lugar declaró el Sr. Néstor Fabián Benke, id. 25511967, comerciante y proveedor de frutas y verduras del Bar Español desde hace unos 10 a 12 años. Manifestó que conoce al actor sólo de vista y que tiene relación comercial con Cristian Orúe, dueño del Bar Español, a quien provee mercadería. Explicó que los pedidos se los envía Cristian por teléfono, que él entrega entre las 7 y las 9 horas, dejando los productos en la cocina. Indicó que los cocineros recepcionan la mercadería, aunque a veces no controlan, y que no se firman remitos: deja la mercadería, envía factura por WhatsApp y luego Cristian le paga por transferencia. Mencionó que existe una relación de confianza en la entrega.
En las repreguntas, señaló que desconoce los nombres de los cocineros que reciben los productos, que Cristian suele estar en la caja, y que en ocasiones también ve a Regalado. Manifestó que, aun cuando los dueños no están presentes, los cocineros reciben la mercadería. Confirmó que los pedidos siempre los realiza Cristian, y que los pagos se efectúan por transferencia desde su cuenta de Mercado Pago hacia su cuenta del HSBC. No recordó desde qué banco se operaba antes del uso de Mercado Pago.
Por último declaró la Sra. Silvina Alejandra Rubin, id. 25514622, empleada, quien manifestó conocer al actor en el ámbito laboral y al Bar Español por haber trabajado allí. Indicó trabajar actualmente en otro local (“La Italiana”), también de los mismos dueños. Señaló que conoce al actor desde aproximadamente 2017 y que en el Bar Español él se desempeñaba como cajero. Declaró haber trabajado en el bar desde 2017 hasta 2024, como moza, con horario de 8 a 16 hs, registrada como jornada completa. Explicó que cobraba el sueldo en efectivo, entre el 1 y el 10 de cada mes, sin cuenta sueldo habilitada. Refirió que dejó el empleo porque pasó a trabajar en “La Italiana”. 
Aportó detalles sobre el funcionamiento interno del establecimiento, indicando que los dueños se ocupaban del manejo de personal, contrataciones, despidos, atención a proveedores, pagos, administración y controles impositivos y municipales; que el control de stock estaba a cargo de la cocina; y que el cajero Cavallero atendía a los proveedores en ausencia de los dueños, suscribía remitos, abonaba adelantos por orden de éstos y cumplía horario de 17 a 01 horas. Explicó que los proveedores ingresaban por el salón hacia la cocina, recibiendo mercadería de verdulería a las 6 horas y otros productos entre las 8 y 10 horas, y que cuando los dueños no estaban, se comunicaban con el cajero. Agregó que, por orden de éste, llegó a trasladar un pedido de cafetería a otro comercio (Alperín). Señaló además que los empleados cumplían funciones acordes a su categoría, que no conoció reclamos por incorrecta registración o salarios y que no recordaba el nombre del proveedor de verduras.
Ahora bien, corresponde valorar los testimonios producidos conforme las reglas de la sana crítica racional, atendiendo a la coherencia, verosimilitud, percepción directa, imparcialidad, concordancia entre las declaraciones y compatibilidad con el resto de la prueba.
De los testigos Aníbal Ricardo Kuhn, Cristian Jhonatan Barrios, Ricardo Rodrigo Fernández y Jorge Antonio Azame, todos ex dependientes del Bar Español SRL, declararon haber trabajado junto al actor durante extensos períodos —algunos desde 2005 hasta fechas cercanas a la desvinculación—, circunstancia que les confiere percepción directa, habitual y prolongada sobre su desenvolvimiento funcional.
Los testigos describieron una amplia gama de tareas de jerarquía y administración realizadas por el actor, tales como: apertura y cierre del local (con manejo de llaves/alarmas), manejo de personal (organización de francos, vacaciones, horarios, contratación y despido), gestión administrativa/financiera (realización de depósitos, pagos, sueldos, vales, trámites ante AFIP y Municipalidad, recepción de proveedores), y representación del establecimiento ante inspecciones y en ausencia de los dueños.
Todos los testigos coinciden en que tales tareas eran permanentes, habituales y propias de un encargado general, no esporádicas ni accidentales. Asimismo, relatan condiciones laborales irregulares —personal no registrado, vales, jornadas prolongadas, pagos fraccionados— que contextualizan la existencia de una desnaturalización funcional, consistente con el reclamo del actor.
Que la concordancia sustancial entre los cuatro testimonios, su coherencia interna, su carácter descriptivo —detallando hechos concretos y no meras opiniones— y la percepción directa por haber compartido el mismo ámbito laboral por largos períodos otorgan a esta prueba alta fuerza convictiva, suficiente para tener por acreditadas las tareas invocadas por el actor. Además estas declaraciones se encuentran respaldadas con la debida razón de sus dichos, esto es las circunstancias de tiempo, modo y lugar que tornan verosímil el conocimiento de los hechos relatados por los declarantes en cuanto al desempeño de las tareas relatadas.
Por otro lado, los testimonios aportados por la demandada carecen de fuerza convictiva suficiente para desvirtuar las tareas jerárquicas atribuidas al actor. En primer lugar, dos de los tres testigos —Cavallero y Rubin— son empleados actuales del mismo grupo empleador, situación que compromete su imparcialidad por la evidente relación de subordinación económica. A ello se suma que ambos brindan relatos genéricos y negativos, sin describir de modo concreto qué tareas veían realizar al actor, limitándose a afirmar que las funciones administrativas, de personal o de proveedores eran realizadas por los dueños, sin aportar detalles que contradigan la prueba producida por la actora. También presentan conocimientos parciales: Cavallero ingresó recién en 2014 y Rubin trabajó sólo en horario diurno, sin cubrir la totalidad de los turnos donde los testigos del actor ubicaron las tareas jerárquicas del demandante. Por su parte, el testigo Benke, proveedor externo, no posee aptitud probatoria para acreditar las funciones internas del actor, ya que su presencia se restringe a entregas breves de mercadería en la mañana, desconociendo la dinámica administrativa y organizativa del local.
En conjunto, todos ellos ofrecen información incompleta, fragmentaria y con escaso detalle, sin contradicciones reales respecto de los hechos precisos narrados por los testigos del actor. Por ello, sus declaraciones no resultan idóneas para desvirtuar la convincente prueba testimonial producida por el trabajador sobre el efectivo desempeño de tareas que exceden las propias de un cajero adicionista y que los testigos describen como de “encargado general”.
De la valoración integral de la prueba producida, y en particular de la prueba testimonial rendida en autos, se tiene por acreditado que el Sr. Regalado desarrolló tareas que excedían las propias de un simple cajero adicionista, tal como se encontraba formalmente registrado. En efecto, los testigos de la actora describieron la asunción habitual y permanente de funciones de mayor responsabilidad, vinculadas a la organización cotidiana del establecimiento, coordinación del personal, manejo operativo y administrativo básico, así como la atención de situaciones funcionales en ausencia de los titulares del negocio.
Ahora bien, ello no implica sin más que tales tareas encuadren necesariamente en la Categoría 6 (“Encargado”) del CCT Nº 389/04, tal como fuera postulada por el actor. En efecto, del propio texto convencional surge que, dentro del ámbito de los establecimientos gastronómicos (art. 10.1.c CCT 389/04), la categoría 6 comprende funciones específicas y típicas de barman, cafetero vendedor, capataz o encargado de parrilla, capataz de sala, chef de fila, fiambrero, jefe de partida, maître, maestro de pala pizzero, maestro facturero, mozo, postrero y rotisero. Tales funciones que no se corresponden de manera directa ni específica con las tareas descriptas por los testigos, quienes no atribuyen al actor ninguna de esas funciones técnicas u operativas propias del listado convencional.
Cabe destacar que el CCT Nº 389/04 no contempla de modo expreso la figura autónoma de “encargado general” para establecimientos gastronómicos, sino que organiza las categorías en función de tareas concretas y tipificadas. En tal contexto, si bien se acreditó que el actor asumió funciones que excedían las de un cajero adicionista, no se probó que realizara alguna de las tareas específicas previstas para la categoría 6 del ordenamiento convencional que reclama.
Las funciones relatadas —organización básica del personal, control operativo, enlace con la patronal, manejo de valores, coordinación diaria del funcionamiento— resultan más compatibles con una categoría propia de un empleado principal administrativo o cajero con funciones ampliadas, encuadrables dentro de la Categoría 5 del CCT Nº 389/04 (coincidente con la registrada), en aplicación del principio de movilidad funcional, en tanto dichas tareas se mantienen dentro del marco de actividades reguladas por el convenio.
Por otro lado, y en atención a que varias de las funciones descriptas por los testigos —tales como decisiones organizativas amplias, representación del establecimiento frente a terceros y asunción de responsabilidades generales— no se encuentran específicamente reguladas por el CCT, cabe concluir que, corresponden a un empleado jerárquico fuera de convenio (art. 6.2 CCT 389/04), sin que ello habilite, en forma automática, la aplicación de la categoría 6 pretendida.
En consecuencia, no corresponde asignarle la categoría 6 del CCT Nº 389/04 pretendida, sino reconocer que las tareas efectivamente desarrolladas excedían las del cajero adicionista, encuadrando en funciones jerárquicas no contempladas por el convenio.
II.- Diferencias salariales
El actor en el “punto III liquidación” reclama diferencias salariales, pero del resto del escrito de demanda no surge ninguna otra referencia para establecer la pretensión. 
Sin embargo acompaña en id. 22256886 una planilla de diferencias salariales, donde reclama desde enero del 2021 hasta diciembre del 2022 la suma de $155.093,21 por la diferente categoría.
En efecto, toda vez que el reclamo de diferencias salariales se apoya en la pretensión de encuadrar al actor en la Categoría 6 (“Encargado”) del CCT Nº 389/04, el mismo no puede prosperar, por cuanto no se ha acreditado que las tareas efectivamente desarrolladas se correspondan con las funciones específicas y tipificadas previstas para dicha categoría convencional, resultando improcedente la liquidación practicada sobre esa base.
Tal como se mencionara antes, las tareas correspondientes a la categoría 6 no se asemejan siquiera a las realizadas por el trabajador. Genéricamente se atribuye la calidad de “encargado”, sin embargo resulta ajena a la grilla del Convenio Colectivo de Trabajo aplicable (CCT 389/04). Estas funciones adicionales, por su naturaleza jerárquica y autonomía, son características típicas del "personal fuera de convenio".
El escrito de inicio traba la litis en términos estrictos: el accionante reclama el encuadramiento en la "Categoría 6" del CCT. El problema que se suscita es que el actor no acreditó realizar las tareas específicas que la norma convencional asigna a dicha Categoría 6, sino que probó realizar otras distintas, de mayor jerarquía y extra-convencionales.
Si bien rige en nuestro ordenamiento el principio iura novit curia, por el cual el juez tiene la facultad y el deber de calificar jurídicamente los hechos expuestos por las partes, dicha potestad encuentra un límite infranqueable en el principio de congruencia (arts. 34 inc. 4 y 164 inc. 6 del CPCCFyVF). El juez puede suplir o corregir el derecho invocado, pero no puede alterar la base fáctica ni el objeto de la pretensión sin vulnerar la garantía constitucional de defensa en juicio (art. 18 C.N.).
En el caso de marras, modificar la pretensión del actor —quien solicitó específicamente una categoría convencional (Cat. 6)— para otorgarle un reconocimiento como "personal fuera de convenio", implicaría una modificación sustancial de la pretensión. No se trata de encuadrar la pretensión según una categoría convencional distinta a la reclamada y según las tareas acreditadas (ultra petita); sino de establecer la existencia de diferencias salariales por "fuera de convenio", aspecto sobre el que nada se argumentó y el demandado no ejerció su defensa.
Admitir la pretensión en estas condiciones constituiría un vicio de incongruencia en la modalidad de fallo extra petita (otorgar algo distinto a lo peticionado). 
Al no verificarse la subsunción de los hechos en la norma invocada por el actor (descripción de tareas de la categoría 6; art. 10.1.c CCT 389/04), la pretensión debe ser rechazada. No es posible, sin vulnerar el principio de congruencia, reconducir el reclamo hacia un encuadramiento "fuera de convenio" que el propio actor omitió plantear, pues ello implicaría fallar sobre una cuestión no sometida a litigio. 
III.-Intercambio telegráfico.
Puede observarse de las misivas obrantes en el expediente que en fecha 26/05/2022 el trabajador remitió telegrama a su empleador rechazando e impugnando la sanción disciplinaria por el supuesto hecho de violencia verbal y física con un compañero de trabajo. Solicitó se deje sin efecto, bajo apercibimiento de accionar administrativo y judicialmente por el cobro de los salarios caídos.    
Posterior a ello, en fecha 27/05/2022 el empleador contestó ratificando la sanción impuesta, manifestando que los hechos quedaron grabados en las imágenes de la cámara de seguridad del negocio. Asimismo expresó que debía retomar sus labores el 31 de mayo. 
Luego en fecha 18/10/2022 el Sr. Regalado envió misiva relatando su fecha de ingreso, horarios y funciones. Asimismo expresó que desde el inicio de la relación laboral, la patronal no cumplio con sus obligaciones laborales por cuanto lo registró en como cajero cuando debía ser “categoría 6- encargado”, intimando a que en el plazo de 30 días registre su real categoría y consigne el verdadero salario, bajo apercibimiento de ley. Asimismo lo intimó a que proceda abonar el sueldo correspondiente de  septiembre del 2022 ante la negación del pago, que proceda hacer entrega de los recibos de haberes faltantes, abonar diferencias salariales , aguinaldo, vacaciones, horas extras y francos no otorgados, todo bajo apercibimiento de considerarse despedido  y de reclamar las indemnizaciones previstas por la ley.  
Seguidamente la empleadora, remitió cd 142951565 en fecha 20/10/2022 rechazando la misiva anterior, negando que realizará tareas de encargado, rechazó la supuesta enfermedad de estrés, informando que solicitará una junta médica ante el Ministerio de trabajo a los fines de establecer su real estado de salud.  
Luego hubo un par de telegramas más de ambas partes hasta que finalmente el actor remitió la CD Nº 205099594 el 12/12/2022, manifestando su voluntad de mantener la relación laboral. Sin embargo, ante el tiempo transcurrido y la negativa de la demandada a regularizar correctamente su registración —conforme la real categoría de encargado y la escala salarial del convenio aplicable—, como así también frente a la falta de pago de diferencias salariales, aguinaldos, horas extras, francos trabajados y la omisión en la entrega de los recibos de haberes faltantes, la continuidad del vínculo se tornó imposible. Por ello, se consideró despedido indirectamente. Asimismo, intimó a la empleadora a que, en el plazo de 48 horas, procediera a abonar las diferencias salariales adeudadas, el sueldo de diciembre de 2022, la integración del mes de despido, el aguinaldo proporcional del segundo semestre, las vacaciones proporcionales, la indemnización sustitutiva de preaviso, la indemnización por despido del art. 245 LCT, y las multas previstas en los arts. 24.013 y 1 y 2 de la ley 25.323 (fs. 43). Dicha misiva llegó a la esfera de conocimiento de la empleadora el mismo día conforme surge de la CD siguiente. 
Frente a ello la demandada contestó en fecha 14/12/2022 manifestando que los recibos de sueldo fueron retirados por personas autorizadas por el, que los certificados de servicios y remuneraciones deberá retirarlo de la empresa dentro del plazo de 10 días de realizado el acuerdo. Que su pretensión de darse por despedido por culpa de la empresa obedece a que no tiene intención de afrontar la junta médica requerida por la empresa. 
Ahora bien, una vez determinado el hecho del despido, el cual ocurrió el 12/12/2022, corresponde abocarse al análisis de la injuria en la que funda el distracto.
IV.- La injuria
De conformidad con lo dispuesto por el art. 242 de la LCT, la injuria laboral que habilita el despido indirecto debe revestir entidad suficiente para tornar imposible la prosecución del vínculo, valoración que debe efectuarse ponderando la gravedad objetiva del incumplimiento, su persistencia en el tiempo, la conducta asumida por el empleador frente a los reclamos del trabajador, y el contexto general de la relación.
En el caso bajo análisis, el actor funda su decisión rupturista en una pluralidad de incumplimientos que atribuye a la empleadora, entre ellos: la aplicación de una sanción disciplinaria que consideró injustificada, la incorrecta categorización laboral, la falta de pago de diferencias salariales y otros rubros, y la omisión en la entrega de recibos de haberes.
En primer lugar, respecto de la sanción disciplinaria impuesta en mayo de 2022, surge que el trabajador la impugnó oportunamente y que la empleadora ratificó su postura, invocando la existencia de registros fílmicos del hecho imputado. Sin perjuicio de la discrepancia entre las partes, no se advierte que dicha sanción —aislada en el tiempo y sin constancia de reiteración posterior— haya generado una alteración sustancial del vínculo ni un perjuicio de entidad tal que, por sí sola, habilite la ruptura contractual meses después. La cuestión disciplinaria quedó agotada en ese intercambio epistolar y no se acredita que haya sido utilizada como un mecanismo de hostigamiento ni que haya impedido la continuidad de la relación laboral.
En cuanto a la incorrecta categorización invocada, conforme se resolviera precedentemente, si bien se acreditó que el actor realizaba tareas que excedían las propias de un cajero adicionista, no se probó que dichas funciones encuadren en la Categoría 6 (“Encargado”) del CCT Nº 389/04, base central del reclamo del trabajador. En consecuencia, el incumplimiento imputado a la empleadora no reviste la entidad alegada por el actor, en tanto su intimación se sustentó en una pretensión de categoría que no resultó jurídicamente procedente como se estableciera anteriormente.
Ello permite concluir que la negativa de la demandada a registrar al actor como “encargado categoría 6” no puede calificarse como arbitraria o injustificada, sino que se enmarca en una discrepancia razonable respecto del correcto encuadre convencional de las tareas efectivamente desarrolladas, cuestión que, por su propia naturaleza, no alcanza a configurar una injuria grave en los términos del art. 242 de la LCT.
En igual sentido, el reclamo de diferencias salariales, aguinaldos, horas extras, francos y demás rubros fue formulado en forma genérica y acumulada en la intimación de octubre de 2022, sin que se haya acreditado en autos un incumplimiento salarial grave, persistente y actual que tornara imposible la continuidad del vínculo. En particular, las diferencias salariales reclamadas se encuentran directamente vinculadas a la incorrecta categoría pretendida (categoría 6), que fue desestimada, lo cual debilita sustancialmente el fundamento económico del distracto.
Tampoco se acreditó que la empleadora haya adoptado una conducta renuente o contumaz frente a los reclamos del actor. Por el contrario, la demandada respondió las intimaciones, negó los extremos invocados, manifestó su voluntad de someter la cuestión médica a una junta ante la autoridad administrativa y no impidió el reintegro del trabajador a sus tareas, extremo que incluso fue reconocido por el propio actor en la CD del 12/12/2022 al manifestar su voluntad de mantener la relación laboral.
Este último aspecto resulta particularmente relevante, ya que evidencia que, aun a escasos días del distracto, el propio trabajador no consideraba objetivamente imposible la prosecución del vínculo, lo cual desdibuja la alegada gravedad de la injuria y conspira contra la configuración del presupuesto exigido por el art. 242 LCT.
En conclusión, los incumplimientos analizados no tienen la gravedad necesaria para justificar que el trabajador se diera por despedido. Se trata de una diferencia de criterios sobre el cobro de ciertos rubros y la categoría laboral, que podría haberse resuelto sin romper el contrato, de acuerdo con el principio de conservación del vínculo. Sobre todo teniendo en cuenta la relación de confianza establecida en virtud del vínculo familiar del actor con uno de los socios.
Por ello, corresponde concluir que el despido indirecto dispuesto por el actor el 12/12/2022 no se encuentra justificado, con las consecuencias legales que de ello se derivan.
Por todo lo expuesto, y valorando la prueba producida conforme las reglas de la sana crítica racional, corresponde concluir que el actor no ha logrado acreditar la existencia de una injuria de entidad suficiente en los términos del art. 242 de la LCT que tornara imposible la prosecución del vínculo laboral, razón por la cual el despido indirecto en que se colocó en fecha 12/12/2022 resulta injustificado, debiendo rechazarse las indemnizaciones derivadas del despido reclamadas en autos.
V.- Art. 10 y 15 Ley 24013
Sin realizar manifestación ni expresar argumento alguno, el actor reclama en su planilla la indemnización establecida en el art. 10 de la ley 24013 así como el incremento indemnizatorio del art.15 de la LNE. 
El art. 10 LNE supone la existencia de pagos sin la debida registración. Esto es lo que habitualmente se conoce como pagos “en negro” o bien el registro de sumas inferiores a las efectivamente percibidas por el trabajador. 
Sostiene el trabajador que “desde el inicio de la relación laboral, la patronal no cumplió con sus obligaciones laborales por cuanto registro al suscripto en una categoría distinta de la real, es por ello que en virtud de los arts. 10, 11 y 15 de la Ley Nacional de Empleo N° 24013 intimé... registre correctamente mi real categoría y consignen el verdadero salario…”. Ello evidencia que relaciona, incorrectamente, el reclamo con la registración de la categoría y las diferencias que de ella devengarán, aspecto que ya fuera tratado y que aleja la procedencia del rubro.
Aun asi, denuncia que luego de conversar con su hermana, la Sra. Debora Regalado, socia de la SRL, “...comenzaron a abonarme en algunas ocasiones un importe de dinero en negro, independiente del recibo de haberes…”.
Por su parte la demandada reconoce, en el contexto de la relación familiar, que “la socia Debora Regalado todos los meses otorgaba a su hermano una “gratificación” por fuera del sueldo que resultaba una ayuda familiar en la que la mayoría de las veces el esposo y socio gerente no tenía conocimiento…”.  
Pese a las diversas irregularidades señaladas por los testigos, ninguno afirmó que Regalado, quien se encontraba registrado en jornada completa, percibiera sumas no registradas. No se invoca, ni acredita, los montos ni la frecuencia con que ello ocurría. Menos aún resulta desvirtuada la versión dada por la demandada que se apoya en la relación familiar habida entre el actor y la socia Debora Regalado, quien no ejercía la representación de la sociedad.
En consecuencia la indemnización no puede prosperar, así como tampoco el incremento indemnizatorio del art. 15 LNE. Lo propio ocurre respecto de la indemnización del art. 1 de la ley 25.323 reclamado en forma supletoria.

VI.- Art. 2 Ley 25.323
La norma invocada sanciona la falta de pago de las indemnizaciones derivadas del despido pese a la intimación que debe efectuar el trabajador. Como consecuencia del rechazo de las pretensiones fundadas en el distracto, esta indemnización tampoco resulta procedente.
VII.- Art. 43 ley 25.345 - art 132 bis LCT
El actor reclama la sanción conminatoria establecida por el artículo 132 bis de la Ley de Contrato de Trabajo. La sanción persigue el efectivo ingreso a los organismos de la seguridad social y sindicales de los importes retenidos al trabajador. 
Según el informe de AFIP, obrante en id. 25400984, la empresa retuvo aportes de seguridad social y obra social de los salarios del Sr. Regalado, pero no los depositó en los organismos correspondientes. Específicamente, surgen impagos 126 meses de aportes de obra social, habiendo ingresado los montos correspondientes a sólo 86 períodos de los 212 trabajados. Surge también la falta de ingreso de los aportes de la seguridad social correspondiente a los meses de marzo a junio de 2020.
Cabe señalar que en oportunidad de la audiencia de exhibición -id 25488602- la demandada exhibió “convenios con el Gremio” y manifestó que “los mismos se encuentran pagados. El convenio es con OSUTHGRA, según se exhiben los mismos en este acto. Los aportes se efectúan mediante el pago del formulario 931 de AFIP”. Por su parte el actor expresó “...con relación al formulario 931 se deja constancia que no se han presentado los comprobantes de pago de aportes previsionales, correspondientes al periodo señalado en audiencia, solamente se han realizados manifestación, sin adjuntar documentación alguna que acredite pago alguno. Que en virtud el convenio de pago, referido con OSUTHGRA el mismo hace referencia a Obra social seguro de vida y sepelio fondo convenio y cuota social, no refiriéndose a pago de aportes previsionales”. 
Pese a lo señalado por el actor; respecto de que “en ninguna de sus cláusulas expresa el periodo convenido con el sindicato como así también los datos a los empleados a quien o quienes forman parte de este convenio”; la realización voluntaria de convenios de pago con la obra social sindical respecto de los aportes conjura, a los fines de la sanción conminatoria, el incumplimiento respecto de tales aportes.

Resta analizar la procedencia respecto de los aportes a la seguridad social.
Aquí se encuentran acreditados los requisitos formales de procedencia de la sanción, en tanto el trabajador envió una misiva, fs. 43 -TCL Nº205099594 en fecha 12/12/2022 al domicilio del empleador en la que denunciaba la falta de ingreso de los importes retenidos e intimaba a hacerlo, invocando el apercibimiento de la sanción conminatoria del art. 132 bis. En su alegato la demandada manifestó que las multas y sanciones ya no merecen tratamiento por cuanto fueron eliminadas con la aprobación del Decreto de Necesidad y Urgencia nº 70/2023.
Ahora bien, el despido ocurrió el 12/12/2022. A esa fecha, el art. 132 bis LCT se encontraba plenamente vigente, imponiendo la sanción al empleador que, habiendo retenido aportes al trabajador, no los ingresa a los organismos correspondientes. El Decreto 70/23 fue dictado el 20/12/2023, es decir un año después del despido. Conforme al art. 7 del Código Civil y Comercial de la Nación, las leyes no tienen efecto retroactivo, salvo disposición expresa en contrario, lo que no ocurre en el DNU 70/23. El mismo argumento resulta aplicable respecto de la derogación dispuesta por la ley 27742, vigente a partir del 09/07/2024.
Ello implica el devengamiento de la multa a favor del trabajador, tal como establece el art. 132 bis, computando mensualmente la remuneración que le correspondía percibir a la época de la extinción del vínculo, correspondiente al mes de diciembre/2022 ($93.669,16) a partir del período siguiente posterior al momento del distracto, esto es enero de 2023 hasta el mes de enero/2026 inclusive, computando en definitiva 36 períodos remunerativos, alcanzando la suma de $3.372.089,76 ($93.669,16 x 36). Como se dijera anteriormente la omisión de la empleadora al respecto alcanza a los meses de marzo a junio de 2020.
La Alzada señaló en autos  “Expte. N°149919/2018 Ferreyra Emanuel Alejandro C/ C.G. S.R.L. y Otro/a S/ Acciones Laborales de Trámite Ordinario” (Sentencia 10/05/2022) que “la CSJN en reiterados precedentes ha dicho que, por encima de lo que parecen decir literalmente las leyes, es propio de la interpretación indagar lo que dicen jurídicamente, para lo cual no cabe prescindir de sus palabras, pero tampoco atenerse rigurosamente a ellas, pues la hermenéutica de las mismas debe practicarse siempre evitando darles un sentido que ponga en pugna sus disposiciones, destruyendo las unas por las otras y adoptando como verdadero, el que las concilie y deje a todas con valor y efecto, prefiriéndose aquella inteligencia que no las oponga a los textos constitucionales (C.302, “Chiavarro, Armando y otros c. Federación Gremial del Personal de la Industria de la Carne”, del 11/6/1985). También se ha pronunciado en el sentido de que siempre ha de buscarse una interpretación valiosa de lo que las normas han querido mandar, de suerte que la admisión de soluciones injustas cuando es posible arbitrar otros de mérito opuesto, no resulte incompatible con el fin común de la tarea legislativa como de la judicial (“Gallardo Pedro c. YPF”, del 24/4/1986).
Sobre la sanción del art 132 bis LCT en particular la CSJN sostuvo que es inconstitucional el art. 132 bis de la LCT pues la irrazonabilidad de la aplicación de la norma al caso queda puesta de manifiesto, sin más, por la evidente falta de proporcionalidad entre la sanción y su finalidad de prevención o punición de la evasión fiscal; falta de proporcionalidad que obedece a la ausencia de previsión legal que posibilite la graduación de la multa o la inexistencia de todo tope, máxime cuando el incumplimiento oportuno de las obligaciones aquí involucradas ya tiene otras sanciones previstas en el régimen legal impositivo así como en el penal (“Recurso Queja Nº 2 – Domínguez, Yanina Vanesa c/Muresco SA s/despido”: Fallos 347:952 del 13/08/2024)
En ese marco la multa acumulada hasta hoy, según se expusiera anteriormente, no es razonable teniendo en cuenta la gravedad de la falta (el periodo omitido), la duración de relación laboral (18 años) y el tiempo transcurrido desde el distracto (36 meses). 
Es así que corresponde declarar la inconstitucionalidad en el caso concreto del art. 132 bis LCT, en tanto no permite la graduación de la sanción conminatoria (a diferencia de lo que establece el art. 804 CCCN) y reajustar su contenido económico. 
En ese orden la alzada en el expediente antes mencionado (así como en “Expte. N°127469/2016 Acuña Andrea Karina C/ Damus Mauricio Sebastian S/ Acciones Laborales de Tramite Ordinario”, Sala II, sentencia del 21/11/2018), considero adecuado ajustar la sanción conminatoria, consistente en una suma igual al salario devengado por el trabajador, ajustandola al lapso temporal de la falta cometida, estableciendo en la suma de $374.676,64 ($93.669,16 x 4).
VIII.- Intereses
El actor solicita la aplicación de “intereses legales” sin indicar una tasa concreta. No solicita actualización ni composición alguna del crédito.
En ese orden, la suma adeudada devengara intereses, desde que es debida y hasta su efectivo pago, conforme Tasa Activa del Banco de la Nación Argentina, aplicando la capitalización establecida por el art. 770 inc b a la fecha de notificación de la demanda. Todo ello sin perjuicio de lo dispuesto por el art. 770 inc. c CCCN en caso de mora en el cumplimiento de esta sentencia y una vez firme la liquidación practicada.

Rubro
Monto
TABN
Intereses
Art. 132 bis LCT
$376.676,64
80,500%
$303.224,70
Total al 29/09/2023
$679.901,34
151,670%
$1.031.206,36
Total 02/02/2026
$679.901,34


$1.031.206,36


En consecuencia condeno al Bar Español S.R.L a abonar al Sr. Juan José Luján  Regalado la suma de pesos seiscientos setenta y nueve mil novecientos uno con treinta y cuatro centavos ($679.901,34) en concepto de capital con más la suma de pesos un millón treinta y un mil doscientos seis con treinta y seis centavos ($1.031.206,36) en concepto de intereses devengados al 02/02/2026. 
A partir de dicha fecha el capital continuará devengando intereses conforme la Tasa Activa del Banco de la Nación Argentina hasta su efectivo pago.
Todo dentro de los 10 días de quedar firme esta sentencia, bajo apercibimiento de ejecución forzada y de lo dispuesto por el art. 770 inc c Código Civil y Comercial de la Nación.
IX- Costas.
En virtud de la proporción del éxito obtenido por las partes, asi como teniendo en cuenta que el actor debió demandar para obtener el reconocimiento de los derechos que aquí se declaran, corresponde la imposición de las costas a la parte actora en un 80%, con los alcances del art. 20 de la CPL, y a la parte demandada en un 20%, conforme al art. 168 del CPL.
Se deja constancia de que para arribar a ésta solución se han valorado la totalidad de las pruebas producidas en autos, mencionando en esta Sentencia sólo aquella que se estima dirimente a los fines de resolver los aspectos sometidos a decisión (Art 101, CPL, Ley XIII - N°2).
X.- Honorarios:
Corresponde regular honorarios de la parte actora Dra. Karina Itati Acosta, mayormente perdidosa, quien actuó en el doble carácter conforme Ley XII - N° 4.  Así de conformidad a la escala prevista en el art. 16 (70% del 19% y 100% del 19%) estimo adecuado regularlos en un 16%, a los que debe agregarse un 6,4% conforme los arts. 8 y 9 (40% del 16%=4,65%) de la Ley XII Nº 4, ello teniendo en cuenta la labor desplegada. En consecuencia regulo sus honorarios en un 22,4 % de la base arancelaria ($1.711.107,69) que alcanza la suma de $383.288,12, debiendo adicionarse el IVA en caso de corresponder.
 Finalmente, corresponde regular honorarios del Dr. Edmundo Raul Maldonado quien actúo en representación de la parte demandada, Ley XII - N° 4, Art. 14 en un 21% y por los arts. 8 y 9 en un 40% de aquel (8,4%), lo que hace un 29,4% de la base arancelaria, resultando la suma de $503.065,66, debiendo adicionarse el IVA en caso de corresponder.
SENTENCIO:
I.- DECLARAR LA INCONSTITUCIONALIDAD del art. 132 bis LCT, con los alcances y por los argumentos expuestos precedentemente en el apartado VII.
II.- HACER LUGAR parcialmente a la demanda, únicamente respecto de la sanción conminatoria del art. 132 bis LCT reclamada y por tanto CONDENAR a Bar Español S.R.L a abonar al Sr. Juan José Luján  Regalado la suma de pesos seiscientos setenta y nueve mil novecientos uno con treinta y cuatro centavos ($679.901,34) en concepto de capital con más la suma de pesos un millón treinta y un mil doscientos seis con treinta y seis centavos ($1.031.206,36) en concepto de intereses devengados al 02/02/2026. A partir de dicha fecha el capital continuará devengando intereses conforme la Tasa Activa del Banco de la Nación Argentina hasta su efectivo pago. Todo dentro de los 10 días de quedar firme esta sentencia, bajo apercibimiento de ejecución forzada y de lo dispuesto por el art. 770 inc c Código Civil y Comercial de la Nación.
III.- RECHAZAR parcialmente la demanda interpuesta por el Sr. Juan José Luján Regalado en contra del Bar Español S.R.L, respecto de las indemnizaciones derivadas del despido indirecto, diferencias salariales, arts. 10 y 15 Ley 24.013, y arts. 1 y 2 ley 25.323, por los argumentos expuestos precedentemente.
IV.- IMPONER las costas a la parte actora en un 80%, con los alcances del art. 20 de la CPL, y a la parte demandada en un 20%, conforme al art. 168 del CPL. 
V.- REGULAR LOS HONORARIOS de la Dra. Karina Itati Acosta en la suma de $383.288,12, debiendo adicionarse el IVA en caso de corresponder. Notificar la presente al domicilio real de su poderdante, en los términos del art. 38 de la Ley XII N° 4.
VI.- REGULAR LOS HONORARIOS del Dr. Edmundo Raul Maldonado,  en la suma de $503.065,66, debiendo adicionarse el IVA en caso de corresponder. Notificar la presente al domicilio real de su poderdante, en los términos del art. 38 de la Ley XII N° 4.
VII.-REQUERIR a la parte actora que denuncie y acredite en autos cuenta bancaria de su titularidad informando Número de cuenta, CBU de la misma e institución bancaria a la que pertenece.
VIII.- Tener presente la cuenta bancaria abierta en el Banco Macro SA, a la orden del juzgado y carátula de las presentes, id 24862481.
REGÍSTRESE. NOTIFÍQUESE. Firme que quede la presente, gírense las actuaciones a los efectos que se liquide el Fondo de Justicia y oportunamente ARCHÍVESE."""
# -------------------------------------------------------

url = "http://127.0.0.1:8000/analizar-borrador/"
datos = {
    "texto_borrador": texto_real,
    "nombre_archivo": "Prueba_Real_Juez.docx"
}

try:
    print("⏳ Enviando borrador al Cerebro IA... (Espere unos segundos)")
    respuesta = requests.post(url, json=datos)
    
    if respuesta.status_code == 200:
        info = respuesta.json()
        print("\n" + "="*50)
        print("✅ REPORTE RECIBIDO:")
        print("="*50 + "\n")
        print(info["informe_ia"])
        print("\n" + "="*50)
    else:
        print("❌ Error:", respuesta.text)
except Exception as e:
    print("❌ Error de conexión:", e)
